// ModelDefaults.localAssetImageMap supplied by the user, 2026-09-08.
// Character IDs and virtual Cortex entries are not external model providers.
export const FAMILY_ASSETS = Object.freeze({
    "arcee": "assets/producers/arceeai.webp",
    "muse": "assets/models/muse.webp",
    "nemotron": "assets/producers/nvidia.webp",
    "mistral": "assets/models/mistral.webp",
    "kimi": "assets/producers/moonshotai.webp",
    "glm": "assets/producers/z.ai.webp",
    "granite": "assets/producers/ibm.webp",
    "runway": "assets/producers/runway.webp",
    "gpt": "assets/producers/openai.webp",
    "chatgpt": "assets/producers/openai.webp",
    "claude": "assets/models/claude.webp",
    "codex": "assets/models/codex.webp",
    "deepseek": "assets/models/deepseek.webp",
    "gpt-image": "assets/producers/openai.webp",
    "qwen": "assets/models/qwen.webp",
    "qwen-image": "assets/models/qwen.webp",
    "gemini": "assets/models/gemini.webp",
    "lyria": "assets/models/lyria.webp",
    "gemma": "assets/models/gemma.webp",
    "grok": "assets/models/grok.webp",
    "xai-image": "assets/producers/xai.webp",
    "hermes": "assets/models/hermes.webp",
    "codestral": "assets/models/codestral.webp",
    "mai": "assets/models/mai.webp",
    "ministral": "assets/models/ministral.webp",
    "mixtral": "assets/models/mixtral.webp",
    "pixtral": "assets/models/pixtral.webp",
    "magistral": "assets/models/magistral.webp",
    "devstral": "assets/models/devstral.webp",
    "phi": "assets/models/phi.webp",
    "wizardlm": "assets/models/wizardlm.webp",
    "tinyllama": "assets/models/tinyllama.webp",
    "llama": "assets/models/llama.webp",
    "command": "assets/models/cohere.webp",
    "nova": "assets/models/nova.webp",
    "perplexity": "assets/models/perplexity.webp",
    "lfm": "assets/producers/liquidai.webp",
    "flux": "assets/models/flux.webp",
    "ideogram": "assets/models/ideogram.webp",
    "imagen": "assets/models/imagen.webp",
    "kling": "assets/models/kling.webp",
    "pixverse": "assets/models/pixverse.webp",
    "sdxl": "assets/models/sdxl.webp",
    "sora": "assets/models/sora.webp",
    "topaz": "assets/models/topaz.webp",
    "wan": "assets/models/wan.webp",
    "z-image": "assets/producers/z.ai.webp",
    "bria": "assets/models/bria.webp",
    "bytedance": "assets/models/bytedance.webp",
    "seedance": "assets/models/seedance.webp",
    "seedream": "assets/models/seedream.webp",
    "minimax": "assets/producers/minimax.webp",
    "elevenlabs": "assets/models/elevenlabs.webp",
    "ernie": "assets/models/ernie.webp",
    "fabric": "assets/models/cohere.webp",
    "veo": "assets/models/veo.webp",
    "seedvr": "assets/producers/seedvr.webp",
    "grok-imagine": "assets/models/grok.webp",
    "suno": "assets/models/suno.webp",
    "musicgen": "assets/models/meta.webp",
    "stable": "assets/models/stable.webp",
    "stable-audio": "assets/models/stable.webp",
    "whisper": "assets/models/whisper.webp",
    "banana": "assets/models/banana.webp"
});
export const PRODUCER_ASSETS = Object.freeze({
    "openai": "assets/producers/openai.webp",
    "anthropic": "assets/producers/anthropic.webp",
    "amazon": "assets/producers/amazon.webp",
    "google": "assets/producers/google.webp",
    "xai": "assets/producers/xai.webp",
    "arcee": "assets/producers/arceeai.webp",
    "nousresearch": "assets/producers/nousresearch.webp",
    "mistral": "assets/models/mistral.webp",
    "microsoft": "assets/producers/microsoft.webp",
    "meta": "assets/models/meta.webp",
    "cohere": "assets/models/cohere.webp",
    "unsloth": "assets/producers/unslothai.webp",
    "menlo": "assets/producers/menloresearch.webp",
    "thebloke": "assets/producers/thebloke.webp",
    "snowflake": "assets/producers/snowflake.webp",
    "secondstate": "assets/producers/secondstate.webp",
    "modular": "assets/producers/modularai.webp",
    "intel": "assets/producers/intel.webp",
    "ggml": "assets/producers/ggmlorg.webp",
    "fortytwonetwork": "assets/producers/fortytwonetwork.webp",
    "devquasar": "assets/producers/devquasar.webp",
    "defog": "assets/producers/defogai.webp",
    "lamapi": "assets/producers/lamapi.webp",
    "liquid": "assets/producers/liquidai.webp",
    "mazyarpanahi": "assets/producers/maziyarpanahi.webp",
    "maziyarpanahi": "assets/producers/maziyarpanahi.webp",
    "neuphonic": "assets/producers/neuphonic.webp",
    "jetbrains": "assets/producers/jetbrains.webp",
    "zed": "assets/producers/zed.webp",
    "lm": "assets/producers/lmstudiocommunity.webp",
    "midjourney": "assets/producers/midjourney.webp",
    "runway": "assets/producers/runway.webp",
    "veed": "assets/producers/veed.webp",
    "moonshot": "assets/producers/moonshotai.webp",
    "z.ai": "assets/producers/z.ai.webp",
    "ibm": "assets/producers/ibm.webp",
    "inclusion": "assets/producers/inclusionai.webp",
    "nvidia": "assets/producers/nvidia.webp"
});

// Explicit presentation identities. A producer logo never authorizes a family.
export const FAMILY_NAMES = Object.freeze({
    arcee: 'Arcee AI',
    gpt: 'ChatGPT', chatgpt: 'ChatGPT', claude: 'Claude', codex: 'Codex',
    deepseek: 'DeepSeek', 'gpt-image': 'GPT Image', qwen: 'Qwen', 'qwen-image': 'Qwen',
    gemini: 'Gemini', lyria: 'Lyria', gemma: 'Gemma', grok: 'Grok', 'xai-image': 'Grok',
    hermes: 'Hermes', mai: 'MAI', muse: 'Muse', nemotron: 'Nemotron',
    mistral: 'Mistral', ministral: 'Ministral', mixtral: 'Mixtral', pixtral: 'Pixtral',
    magistral: 'Magistral', devstral: 'Devstral', codestral: 'Codestral', phi: 'Phi',
    wizardlm: 'WizardLM', tinyllama: 'TinyLlama', llama: 'Llama', command: 'Command',
    nova: 'Nova', perplexity: 'Perplexity', lfm: 'LFM', flux: 'Flux', ideogram: 'Ideogram',
    imagen: 'Imagen', kling: 'Kling', pixverse: 'PixVerse', sdxl: 'Stable', sora: 'Sora',
    topaz: 'Topaz', wan: 'Wan', 'z-image': 'Z Image', bria: 'Bria',
    seedance: 'Seedance', seedream: 'Seedream', minimax: 'MiniMax',
    elevenlabs: 'ElevenLabs', ernie: 'Ernie', fabric: 'Fabric', veo: 'Veo', seedvr: 'SeedVR',
    'grok-imagine': 'Grok', suno: 'Suno', musicgen: 'MusicGen', stable: 'Stable',
    'stable-audio': 'Stable', whisper: 'Whisper', banana: 'Nano Banana',
    kimi: 'Kimi', glm: 'GLM', granite: 'Granite', runway: 'Runway',
});
